### ISSUE TITLE
Is this discontinued?

### ISSUE THREAD

**Issue by cassianomon** [TobiasWalle/rush#2]
Hello, I am starting to learn React then I had your repository saved from some time ago, is this still working? Because I followed the steps and got a error on project generation:

```
Create the project folder "myapp".
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module '../configuration'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.createInitialDefaultConfiguration (/usr/local/lib/node_modules/generator-rush/utils/yo-rc-utils.js:9:25)
    at module.exports.writing (/usr/local/lib/node_modules/generator-rush/generators/app/index.js:165:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-rush/node_modules/yeoman-generator/lib/index.js:417:23)
    at /usr/local/lib/node_modules/generator-rush/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-rush/node_modules/run-async/index.js:24:19
Emitted 'error' event at:
    at Immediate.<anonymous> (/usr/local/lib/node_modules/generator-rush/node_modules/yeoman-generator/lib/index.js:424:16)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
```

**Comment by TobiasWalle** [comment]
Hello @cassianomon, thank you for your issue.
I currently don't find the time to continue this project. But I have plans in the future to completly overthink this library and make a rewrite with a simpler structure.

But at the moment I don't recommend using it. I 'm going to add a disclaimer in the readme for that.

**Comment by cassianomon** [comment]
Thank you for your answer, as a React newbie I find your project idea very intersting.
